-- 1  List the number of films per category.
 
 USE sakila;

SELECT COUNT(FCAT.film_id) AS "Number of films", CAT.name
FROM category AS CAT
JOIN film_category AS FCAT
ON CAT.category_id = FCAT.category_ID
GROUP BY CAT.name;


-- 2  Retrieve the store ID, city, and country for each store.

SELECT store.store_id, city.city, country.country
FROM address
JOIN store
ON address.address_id = store.address_id
JOIN city 
ON address.city_id = city.city_id
JOIN country
ON country.country_id = city.country_id;


-- 3 Calculate the total revenue generated by each store in dollars.

SELECT s.store_id,
SUM(p.amount) AS total_revenue
FROM store AS s
JOIN inventory AS i
	ON s.store_id = i.store_id
JOIN rental AS r
	ON i.inventory_id = r.inventory_id
JOIN payment AS p
	ON r.rental_id = p.rental_id
GROUP BY s.store_id;

-- 4 Determine the average running time of films for each category.

SELECT
	c.name AS category, 
	AVG (f.length) AS average_length
FROM category AS c
JOIN film_category AS fc
	ON c.category_id = fc.category_id
JOIN film AS f
	ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY average_length DESC;
